### ISSUE TITLE
Replace Portable.BountyCastle dependancy with new BountyCastle.Cryprography

### ISSUE THREAD

**Issue by mblataric** [ks-no/fiks-asice-dotnet#120]
Hi, 

Would it possible to replace Portable.BountyCastle dependancy with new BountyCastle.Cryptography? 

I get conflicts because other packages moved to newer version, so now I get both. 

Thanks, 
Mario

**Comment by jarleborsheim** [comment]
Yes, we will look into it 👍

**Comment by mblataric** [comment]
Great, many thanks!
